# Generated by Django 4.1 on 2022-09-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
