# Generated by Django 4.1 on 2022-10-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_paid_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
