# Generated by Django 4.1 on 2022-09-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="paid_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="paid_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
