# Generated by Django 4.1 on 2022-09-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_paid_end_customuser_paid_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="trial_used",
            field=models.BooleanField(default=False),
        ),
    ]
