# Generated by Django 4.1 on 2022-10-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_send_emails_customuser_send_telegrams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="send_emails",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="send_telegrams",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
