# Generated by Django 4.1 on 2022-09-30 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_trial_used"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="paid",
            new_name="active_subscription",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="paid_end",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="paid_start",
        ),
    ]
