# Generated by Django 4.1 on 2022-10-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_send_emails_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="telegram_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="send_emails",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Daily"), (2, "Weekly"), (3, "Disabled")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="send_telegrams",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Daily"), (2, "Weekly"), (3, "Disabled")], default=3
            ),
        ),
    ]
