# Generated by Django 4.1 on 2022-12-28 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_telegram_id_alter_customuser_send_emails_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DemoUserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demo_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
