version: '3.9'

services:
  web:
    image: ideniska/highlights_activator
    build: 
      context: . 
      dockerfile: Dockerfile
    container_name: highlights_activator
    restart: always
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - rabbitmq
  
  celery:
    image: ideniska/highlights_activator
    build: .
    volumes:
      - media_data:/app/media
    env_file:
      - ./.env.dev
    command: celery -A project worker -l info
    entrypoint: ""
    depends_on:
      - web
      - rabbitmq

  db:
    image: postgres:14
    container_name: highlights_activator_db
    restart: always
    volumes:
     - highlights_activator_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - queue_network
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 10s
      timeout: 30s
      retries: 3

  nginx:
    image: nginx:1.19.8-alpine
    container_name: highlights_activator_nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - static_data:/static
      - media_data:/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  highlights_activator_postgres_data:
  static_data:
  media_data:
  rabbitmq:

networks:
  queue_network:
    driver: bridge