version: '3.9'

services:
  web:
    build: ./
    container_name: highlights_activator
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
      #- static_data:/usr/src/app/static
      - media_data:/usr/src/app/media
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: highlights_activator_db
    restart: always
    volumes:
     - highlights_activator_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    container_name: highlights_activator_nginx
    restart: always
    ports:
      - 80:80
    volumes:
      #- static_data:/static
      - ./static:/static
      - media_data:/media
    depends_on:
      - web

volumes:
  highlights_activator_postgres_data:
  static_data:
  media_data:


