# Generated by Django 4.1 on 2022-08-16 16:51

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=core.models.upload_file_path, verbose_name=""
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("kindle", "Kindle"), ("other", "Other")],
                        max_length=30,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="book",
            old_name="book_title_db",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="quote",
            old_name="date_added_db",
            new_name="date_added",
        ),
        migrations.RenameField(
            model_name="quote",
            old_name="quote_db",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="book",
            name="show_status",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="book_title_db",
        ),
        migrations.AddField(
            model_name="book",
            name="visibility",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="book",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="core.book",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="UserFiles",
        ),
    ]
