# Generated by Django 4.1 on 2022-08-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userfile_rename_book_title_db_book_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="quotes_count",
            field=models.IntegerField(default=0),
        ),
    ]
