# Generated by Django 4.1 on 2022-08-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_book_alter_userfiles_file_alter_userfiles_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="owner",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="quote",
            name="owner",
            field=models.IntegerField(),
        ),
    ]
