# Generated by Django 4.1 on 2022-10-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_quote_comment_alter_quote_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="stripe_order_id",
        ),
        migrations.AddField(
            model_name="orders",
            name="stripe_user_email",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
