# Generated by Django 4.1 on 2022-08-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_book_owner_alter_quote_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="owner",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="book",
            name="show_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="userfiles",
            name="file",
            field=models.FileField(upload_to="user_uploads/", verbose_name=""),
        ),
    ]
