# Generated by Django 4.1 on 2022-08-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_book_quotes_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="like",
            field=models.BooleanField(default=False),
        ),
    ]
