# Generated by Django 4.1 on 2022-08-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_book_owner_alter_book_show_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="quotes_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="book",
            name="owner",
            field=models.IntegerField(),
        ),
    ]
