# Generated by Django 4.1 on 2022-09-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_quote_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(default="", max_length=350),
        ),
    ]
