# Generated by Django 4.1 on 2022-09-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_book_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.CharField(default="", max_length=150),
        ),
    ]
