from re import template
from django.urls import path
from . import views

urlpatterns = [
    path(
        "dashboard/",
        views.DashboardPageView.as_view(),
        name="dashboard",
    ),
    path(
        "favorite/",
        views.AuthenticatedTemplateAPIView.as_view(template_name="favorite.html"),
        name="favorite",
    ),
    path(
        "daily/",
        views.AuthenticatedTemplateAPIView.as_view(template_name="daily.html"),
        name="daily",
    ),
    path(
        "share/<id>/",
        views.PageView.as_view(template_name="quote_share.html"),
        name="share",
    ),
    path("", views.PageView.as_view(template_name="landing.html"), name="landing"),
    path(
        "upload/",
        views.AuthenticatedTemplateAPIView.as_view(template_name="upload.html"),
        name="upload",
    ),
    path(
        "upload-progress/",
        views.TemplateAPIView.as_view(template_name="upload_wait.html"),
        name="upload-progress",
    ),
    path("by-book/", views.ByBookView.as_view(), name="by_book"),
    path(
        "by-book-api/",
        views.BooksTemplateAPIView.as_view(template_name="by_book_api.html"),
        name="by-book-api",
    ),
    path("by-book/<int:id>", views.book_inside_view, name="book_page"),
    path(
        "by-book-api/<int:id>",
        views.AuthenticatedTemplateAPIView.as_view(template_name="book_page.html"),
    ),
    path("by-tag/", views.ByTagView.as_view(), name="by_tag"),
    path(
        "logout/",
        views.AuthenticatedTemplateAPIView.as_view(template_name="logout.html"),
        name="logout_page",
    ),
    path(
        "login/",
        views.PageView.as_view(template_name="login.html"),
        name="login_page",
    ),
    path(
        "activate/<uid>/<token>/",
        views.PageView.as_view(template_name="email_activate.html"),
        name="email_activate",
    ),
    path(
        "register/",
        views.PageView.as_view(template_name="register.html"),
        name="register_page",
    ),
    path(
        "activation/",
        views.PageView.as_view(template_name="confirm_email.html"),
        name="activation",
    ),
    path(
        "forgot-password/",
        views.PageView.as_view(template_name="forgot_password.html"),
        name="forgot_password",
    ),
    path(
        "check-email-for-password/",
        views.PageView.as_view(template_name="check_email_for_password.html"),
        name="check_email_for_password",
    ),
    path(
        "set-new-password/<uid>/<token>/",
        views.PageView.as_view(template_name="set_password.html"),
        name="set_new_password",
    ),
    path(
        "settings/",
        views.SettingsPageView.as_view(),
        name="settings",
    ),
    path(
        "create-checkout-session/",
        views.CreateCheckoutSessionView.as_view(),
        name="create-checkout-session",
    ),
    path(
        "create-portal-session/",
        views.CreatePortalSessionView.as_view(),
        name="create-portal-session",
    ),
    path(
        "checkout/monthly/",
        views.AuthenticatedTemplateAPIView.as_view(
            template_name="stripe/checkout_monthly.html"
        ),
        name="checkout_monthly",
    ),
    path(
        "checkout/annual/",
        views.AuthenticatedTemplateAPIView.as_view(
            template_name="stripe/checkout_annual.html"
        ),
        name="checkout_annual",
    ),
    path(
        "stripe/success/",
        views.AuthenticatedTemplateAPIView.as_view(template_name="stripe/success.html"),
        name="success",
    ),
    path(
        "stripe/cancel/",
        views.AuthenticatedTemplateAPIView.as_view(template_name="dashboard_api.html"),
        name="cancel",
    ),
    path("stripe-webhook/", views.StripeWebhook.as_view(), name="stripe_webhook"),
    path(
        "settings/account/",
        views.AuthenticatedTemplateAPIView.as_view(
            template_name="settings/account_settings.html"
        ),
        name="account_settings",
    ),
    path(
        "settings/subscription/",
        views.AuthenticatedTemplateAPIView.as_view(
            template_name="settings/subscription.html"
        ),
        name="subscription",
    ),
    path(
        "demo/",
        views.PageView.as_view(template_name="login_demo.html"),
        name="login_page_demo",
    ),
]
